baseURL = "https://jaekookang.github.io/blog/"
languageCode = "en-us"
title = "Jaekoo Kang"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
disableKinds = ["taxonomy", "taxonomyTerm"]
