baseURL = "https://jaekookang.me/"
languageCode = "en-us"
title = "Jaekoo Kang"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["taxonomy", "taxonomyTerm"]
